### ISSUE TITLE
[Bug Report] Missing `wget` when using docker as provider

### ISSUE THREAD

**Issue by luke0zong** [nyu-devops/lab-bluemix-cf#8]
When using Docker as the Vagrant provider, there will be an error during `Installing IBM Cloud CLI`

at `wget -O bluemix-cli.tar.gz https://clis.cloud.ibm.com/download/bluemix-cli/1.4.0/linux64`

```
    default: ************************************
    default:  Installing IBM Cloud CLI...
    default: ************************************
    default:
    default: sh: 2: wget: not found
```

Seems like the `rofrano/vagrant-provider:debian` image lacks `wget`.

Adding `wget` at the end of
```
apt-get install -y git vim tree python3 python3-pip python3-venv
```
in Vagrantfile solves this problem.

Or simply change the docker image to `rofrano/vagrant-provider:ubuntu` also works.
